### ISSUE TITLE
Timeout::Error

### ISSUE THREAD

**Issue by kegsofduff** [iserko/logstash-input-cloudflare#8]
Hi, 

Thanks for a very useful logstash plugin. It is working for the most part but I'm getting the following error every minute or so. Hoping you can help out. 

Is there a way to increase the request Timeout?

```
{:timestamp=>"2017-03-20T10:40:14.780000-0400", :message=>"Pushing flush onto pipeline", :level=>:debug, :file=>"logstash/pipeline.rb", :line=>"458", :method=>"flush"}
{:timestamp=>"2017-03-20T10:40:15.047000-0400", :message=>Timeout::Error, :level=>:error, :file=>"logstash/inputs/cloudflare.rb", :line=>"300", :method=>"run"}
{:timestamp=>"2017-03-20T10:40:15.047000-0400", :message=>"Timeout::Error", :level=>:error, :file=>"logstash/inputs/cloudflare.rb", :line=>"301", :method=>"run"}
{:timestamp=>"2017-03-20T10:40:15.048000-0400", :message=>"/opt/logstash/vendor/jruby/lib/ruby/1.9/net/protocol.rb:146:in `rbuf_fill'
/opt/logstash/vendor/jruby/lib/ruby/1.9/net/protocol.rb:122:in `readuntil'
/opt/logstash/vendor/jruby/lib/ruby/1.9/net/protocol.rb:132:in `readline'
/opt/logstash/vendor/jruby/lib/ruby/1.9/net/http.rb:2571:in `read_status_line'
/opt/logstash/vendor/jruby/lib/ruby/1.9/net/http.rb:2560:in `read_new'
/opt/logstash/vendor/jruby/lib/ruby/1.9/net/http.rb:1328:in `transport_request'
org/jruby/RubyKernel.java:1242:in `catch'
/opt/logstash/vendor/jruby/lib/ruby/1.9/net/http.rb:1325:in `transport_request'
/opt/logstash/vendor/jruby/lib/ruby/1.9/net/http.rb:1302:in `request'
/home/kegsofduff/logstash-cloudflare/logstash-input-cloudflare-master/lib/logstash/inputs/cloudflare.rb:140:in `cloudflare_api_call'
/opt/logstash/vendor/jruby/lib/ruby/1.9/net/http.rb:746:in `start'
/opt/logstash/vendor/jruby/lib/ruby/1.9/net/http.rb:557:in `start'
/home/kegsofduff/logstash-cloudflare/logstash-input-cloudflare-master/lib/logstash/inputs/cloudflare.rb:133:in `cloudflare_api_call'
/home/kegsofduff/logstash-cloudflare/logstash-input-cloudflare-master/lib/logstash/inputs/cloudflare.rb:203:in `cloudflare_data'
/home/kegsofduff/logstash-cloudflare/logstash-input-cloudflare-master/lib/logstash/inputs/cloudflare.rb:273:in `loop_worker'
/home/kegsofduff/logstash-cloudflare/logstash-input-cloudflare-master/lib/logstash/inputs/cloudflare.rb:297:in `run'
/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.1-java/lib/logstash/pipeline.rb:342:in `inputworker'
/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.1-java/lib/logstash/pipeline.rb:336:in `start_input'", :level=>:error, :file=>"logstash/inputs/cloudflare.rb", :line=>"302", :method=>"run"}
```

Thank you

**Comment by iserko** [comment]
@kegsofduff sorry for missing this one, I'll check it out, but I think it should be possible.

**Comment by iserko** [comment]
@kegsofduff you know after thinking about this problem ... the default timeout is 60 seconds ... I'm very very surprised it managed to time out for you.
